### PR TITLE
DRYing scripts.js file

### PR DESCRIPTION
**Pull request by kaylaewood**
#### What's this PR do?
This PR removed redundancy from the scripts.js file. I consolidated all redundant functions into dynamic functions that use arguments and parameters.

#### Where should the reviewer start?
You should only be looking at the scripts.js file. Look specifically at getStatus & getFriendsInfo

#### How should this be manually tested?
I am not sure how to test this, since it's all DOM manipulation. I just looked at the browser view and refreshed many times to make sure that the images, phrases, and charts were updating correctly as the user changed. @brittanystoroz @khalidwilliams @RaHughes, let me know if there is currently a better way to test this!

#### Any background context you want to provide?
N/A

#### What are the relevant tickets?
This affects ticket #2, but does not close it, as I need to continue working through the other files.

#### Screenshots (if appropriate)
N/A

#### Questions:
- Is there a blog post? N/A
- Does the knowledge base need an update? No
- Does this add new dependencies which need to be added? No

### CODE REVIEW

**Comment by brittanystoroz** [comment]
Very nice PR! I will let your teammate give feedback first, but this is a *perfect* size for a pull request -- significant enough changes to leave feedback on, but not so many that I feel overwhelmed.

**Comment by kaylaewood** [comment]
@brittanystoroz Thank you! If I'm going through each file and DRYing it up, should I create a PR for each file (sleep, activity, etc)? I was planning to do one PR with all changes, but I'm worried it'll be too big.

**Comment by kaylaewood** [comment]
I refactored the following functions on the Activity-Repository.js file:
returnAvgActivityAllUsersByDate
returnActivityByDate
returnActivityByWeek

**Comment by kaylaewood** [comment]
I refactored the following functions on the Sleep-Repository.js file:
returnAverageSleepInfo
returnSleepInfo
returnSleepInfoByWeek

**Comment by kaylaewood** [comment]
I *think* I found all of the glaring non-DRY code. @RaHughes, let me know if you see anything that I missed!

**Comment by kaylaewood** [comment]
I just checked all of the testing to ensure nothing is broken after the refactoring. I had to adjust the functions in the tests to use the updated functions with the correct params. Everything is passing!

**Comment by RaHughes** [comment]
I think this was a huge step in drying up the scripts.js file. The dynamic parameters you've implemented are going to be extremely useful when looking at the rest of the files @kaylaewood. Great work!

**Comment by brittanystoroz** [comment]
@RaHughes Kayla mentioned that she verified that all of the tests are still passing -- this is work that I would expect *you* to do as her partner, rather than trusting her on that. (Not that we don't trust you, Kayla!!) But there are scenarios where things might be working great on Kayla's machine but then be completely broken on yours -- so we'd want you to pull down these changes on the branch and test them out locally for extra assurance.

**Pull request merged**
